#![allow(dead_code, unused_imports)]

mod ch04_01_ownership;
mod ch04_02_references;
mod ch04_03_slices;
mod ch05_structs;
mod ch06_enums;
mod ch08_01_vectors;
mod ch08_02_strings;
mod ch08_03_hashmaps;
mod ch09_errors;
mod ch10_01_generics;
mod ch10_02_traits;
mod ch10_03_lifetimes;
mod ch13_01_closures;
mod ch13_02_iterators;
mod ch15_01_boxes;
mod ch15_04_rc;
mod ch16_01_fearless_concurrency;
mod ch16_02_channel;
mod ch16_03_mutexes;
mod ch19_02_advanced_traits;
mod ch19_02_dogs;
mod ch19_03_adv_types;
mod ch19_04;
mod ch17_oop;
mod iterator;
mod options;
mod primitive_i32;
mod shapes;
mod strings;
mod strs;
mod vectors;

use ch04_01_ownership as ownership;
use ch04_02_references as references;
use ch05_structs as structs;
use ch06_enums as enums;
use ch08_01_vectors as vectors_learning;
use ch08_02_strings as strings_learning;
use ch08_03_hashmaps as hashmaps;
use ch09_errors as errors;
use ch10_01_generics as generics;
use ch10_02_traits as traits;
use ch10_03_lifetimes as lifetimes;
use ch13_01_closures as closures;
use ch13_02_iterators as iterators;
use ch17_oop as oop;

fn main() {
    // ownership::run();
    // references::run();
    // slices::run();
    // structs::run();
    // enums::run();
    // options::run();
    // shapes::run();
    // vectors::run();
    // strings::run();
    // primitive_i32::run();
    // iterator::run();
    // strs::run();
    // vectors_learning::run();
    // strings_learning::run();
    // hashmaps::run();
    // errors::read_to_string();
    // generics::run();
    // traits::run();
    // lifetimes::run();
    // closures::run();
    // iterators::run();
    // oop::run();
    // boxes::run();
    // ch15_04_rc::run();
    // ch16_01_fearless_concurrency::run();
    // ch16_02_channel::run();
    // ch16_03_mutexes::run();
    // ch19_02_advanced_traits::run();
    // ch19_02_dogs::run();
    // ch19_03_adv_types::run();
    ch19_04::run();
}
